@startuml DiagrammeEA

entity Boutique
{
    id 
    ==
    nom
    adresse
}

entity Client
{
    id
    ==
    nom
    prenom
    adresse
    telephone
    email
    mdp
    carte_credit
}

entity Commande
{
    id
    ==
    statut
    date_creation
    date_livraison
    message
    prix
}

entity Bouquet
{
    id
    ==
    nom
    prix
    composition
    categorie
}

entity Fleur
{
    id
    ==
    nom
    prix
    disponibilite
}

entity Accessoire
{
    id
    ==
    nom
    prix
    disponibilite
}

entity Composition
{
    id
    ==
    quantite
}

Client "0,N" --> "1,1" Commande : effectue
Boutique "0,N" --> "1,1" Commande : a reçu

Fleur "1,1" --> "0,N" Boutique : a
Accessoire "1,1" --> "0,N" Boutique : a

Composition "1,1" --> "0,N" Fleur : contient
Composition "1,1" --> "0,N" Accessoire : contient
Composition "1,1" --> "0,N" Bouquet : du bouquet
Composition "1,1" --> "0,N" Boutique : dans la boutique

@enduml